### ISSUE TITLE
Transition callback

### ISSUE THREAD

**Issue by ArcoMul** [ifandelse/machina.js#118]
While implementing a behavioral state machine using Machina.js' implementation I came across a problem where I wanted to track when a state transition was done. So that I could time the next action based on that.

The precise problem I had was that I updated the state of the object in the database in the `_onEnter` function. Often I would call a handler or some other functions directly after calling `this.transition`, these functions would also mess with the data of the same object, and the data had the possibility to be saved wrongly. (Or some other "race condition" would occur)

A possible solution to the problem would be to have the ability to pass a callback in a Machina.js transition. Where my program could wait until the state was saved correctly (after the callback is called), and then continue with the next actions.

Would such a callback fit into the Machina.js design? Or did I solve my problem in the wrong way? Any insights are welcome :-)

**Comment by godspeedelbow** [comment]
+1

**Comment by laander** [comment]
@ArcoMul Interesting, we created a ticket only 6 hours apart on almost the same issue :) https://github.com/ifandelse/machina.js/issues/117

**Comment by ArcoMul** [comment]
@laander Oh woops, and I didn't even read past the title of your issue. I thought it was about something else :no_mouth:

**Comment by laander** [comment]
@ArcoMul No sweat, I guess it simply confirms there is a need for it :+1:

**Comment by ifandelse** [comment]
@laander @ArcoMul Admittedly, I've always felt torn about the fact that machina emits the `transition` event before the `_onEnter` handler fires. Early on I opted for what it does now because it's technically possible for `handle` to be called in an `_onEnter` handler (thus invoking other handlers in that state, etc. as part of the same call stack) and it felt awkward for all of that to happen and _then_ the transition event fire. I'm open to either moving the location of transition to happen after `_onEnter` (as part of a 2.x breaking change) or adding a `transitioned` event like what @laander suggested. 

I also think the idea of a callback is interesting - I've actually played with some ideas along these lines before (they've just never landed in master). That could be a potential follow up to one of the event change ideas I mentioned above. @ArcoMul is your thought here that the callback would be invoked _after_ the `_onEnter` of the new state has fired?

**Comment by ArcoMul** [comment]
No, so my idea is that a `done` callback is passed into the `_onEnter` state. When that `done` callback is called the caller is notified that it can continue, a bit of dummy code might show it the best:

```
// Somewhere in a handler
this.transition('stop', function (arg1, arg2, ...) {
   alert('Yes, done!');
}
...
// _onEnter of the stop state
_onEnter: function (done) {
    $.ajax({
        ...
        success: function (data) {
            done(arg1, arg2, ...);
        }
    });
}
```

So basically a callback "system" doesn't even need to be implemented, but the transition event needs to have the ability to pass parameters to the `_onEnter` function of the state it is transitioning to. (Which might also turn out useful for other use-cases).

**Comment by laander** [comment]
@ifandelse Thanks for the reply. I would prefer the added `transitioned` event as both (before and after _onEnter) might be useful. This way we could also get the change out ASAP as it won't breaking the current API. 

@ArcoMul Working with async methods in machina is hard as state transitions are sync by nature. In your example, I would suggest that you add the async ajax call in the actual handler instead of the transition enter - in that way, when `_onEnter` is called, you can be sure that it's actually transitioned and not in limbo. It makes more conceptual sense too IMO. 
How I'm doing it:
```
// Create a new FSM with states and handlers
var machine = new machina.Fsm({ states: {
off: {
  _onEnter: function() {},
  powerOn: function() {
    return doSomethingAsync
    .then(function() {
      this.transition('on');
    });
  }
},
on: {
  _onEnter: function() { console.log('transitioned to on'); }
}
}});

// Perform the handle and wait for it to finish
machine.handle('powerOn')
.then(function(){
  console.log('handling finished, transitioned to on');
});
```
For added sex appeal, you could mix some ES7 await/async into it and have very readable and pretty methods - here's the powerOn method:
```
  // Wait for the async method to resolve and then make the transition (implicitly returning a promise to the caller)
  powerOn: async function() {
    await doSomethingAsync();
    this.transition('on');
  }
```

**Comment by ifandelse** [comment]
@ArcoMul I agree with @laander's advice - that's how I handle async transitions as well. Another way to consider it would be this: The need for the transition call to execute asynchronously implies there might be a hidden state, or that the transition call shouldn't occur until after the the async operation has completed. If I need to change how I'm responding to other input while the async call hasn't resolved, that's an indicator that I have a hidden state (think of states like `offline`, `connecting`, `connected`, where `connecting` turns out to be the state I wasn't thinking of needing initially).

I have a branch that's a 2.x candidate that I will update to include the `transitioned` event that @laander requested. I will also explore supporting args being passed to `_onEnter`. That's been a feature I've resisted adding in the past (there are other [issue discussions](https://github.com/ifandelse/machina.js/issues/40) covering this), but it's come up enough that I don't want to ignore real needs out there! :-)

**Comment by ArcoMul** [comment]
I see your point, might be that my understanding of states is not correct and I would need to refine that. The `$.ajax` example wasn't my real life problem though. (Sorry about that) I actually have sort of the same problem as what @MichaelJCole describes in the other thread. I'm also saving the state of an object to a Mongo database in the `_onEnter` function, just to make sure that the state isn't lost when the statemachine gets interrupted.

And since this 'object' of which I'm saving the state plays a really central role in the statemachine code I try to prevent to have any code running asynchronously. And thus the statemachine also gets a role as control flow of the code. Which in turn results in the need of having callbacks in some way.

**Comment by ArcoMul** [comment]
Yes I think it isn't implemented by choice. For others still needing this functionality, this is how we solved it now.

We recently implemented a transition wrapper to get callback functionality:
```
transitionAndHandle(this, client, 'asking', 'ask');

...

// Transition to a new state and execute a handle when done
// Relies on states emitting a 'transitionDone' event
function transitionAndHandle(fsm, client, newState, handle) {
    const once = (_client) => {
        offIt();
        fsm.handle(_client, handle);
    };
    function offIt() {
        fsm.off('transitionDone', once);
    }
    fsm.on('transitionDone', once);
    fsm.transition(client, newState);
}
```

So the above examples transitions the state machine to the `asking` state, then listens for the `transitionDone` event, after which it executes the `ask` handler. This way we can do certain database operations in the `_onEnter` of the `asking` state and afterwards do more database operations in the handler, without the two conflicting with each other.

It's not ideal, but works pretty well for us.

**Comment by ArcoMul** [comment]
Sorry, I now see you actually implemented it as functionality. Awesome! Thanks a lot. I will soon try it out for our use-case.
