### ISSUE TITLE
Questions on Hierarchical State Machines

### ISSUE THREAD

**Issue by bedeho** [ifandelse/machina.js#139]
1) My understanding is that, when having a hierarchical state machine, the sub machines have a live as long as the entire machine, even if none of its states are active, is that correct?

2) How does one transition from a state in one sub machine into another state in another sub machine?

**Comment by ifandelse** [comment]
@bedeho Many apologies for taking so long to reply (see #146). To answer your questions:

1. Yes - the child FSM technically lives as long as the parent does. Bear in mind that when the parent FSM is in a state other than the one the child is attached to, any events from the child are ignored.
2. You wouldn't transition from a state in child FSM A directly to a state in child FSM B. Technically, what would happen is that the parent would transition from state 1 (where child A is attached) to state 2 (where child B is attached). Take the [crosswalk example](https://github.com/ifandelse/machina.js#things-suddenly-got-hierarchical) in the readme:

```javascript
var crosswalk = new machina.Fsm( {
    namespace: "crosswalk",
    initialState: "vehiclesEnabled",
    states: {
        vehiclesEnabled: {
            _child: vehicleSignal,
            _onEnter: function() {
                this.emit( "pedestrians", { status: DO_NOT_WALK } );
            },
            timeout: "pedestriansEnabled"
        },
        pedestriansEnabled: {
            _child: pedestrianSignal,
            _onEnter: function() {
                this.emit( "vehicles", { status: RED } );
            },
            timeout: "vehiclesEnabled"
        }
    }
} );
```

The `vehicalSignal` FSM is a child FSM on the crosswalk's `vehiclesEnabled` state. When that child FSM is told to handle a `timeout` event in its `red` state, there's no handler for it, so that input bubbles up to be handled by the parent. The `timeout` handler in the parent's `vehiclesEnabled` state transitions the crosswalk FSM to the `pedestriansEnabled` state. So - the child FSM was told to handle input, but since it didn't have a handler, the parent handled it, giving it the hook it needed to transition the parent to a new state. A similar flow occurs with the `pedestrianSignal` child FSM. I hope that helps!
