### ISSUE TITLE
what does this.deferUntilTransition do?

### ISSUE THREAD

**Issue by atwj** [ifandelse/machina.js#142]
What does it do? I couldn't find any documentation about it anywhere.

Thanks!

**Comment by episage** [comment]
+1

**Comment by episage** [comment]
```
Special "input handlers" exist in machina: _onEnter, _onExit and *. In fact, the very first state (uninitialized) in this FSM is using *. It's the "catch-all" handler which, if provided, will match any input in that state that's not explicitly matched by name. In this case, any input handled in uninitialized will cause the FSM to defer the input (queue it up for replay after transitioning), and immediately transfer to green. (This is just to demonstrate how a start-up-only state can automatically transfer into active state(s) as clients begin using the FSM. )
```

**Comment by ifandelse** [comment]
Thanks for helping answer this @episage 😄 

@atwj There's some info on this in the [wiki](https://github.com/ifandelse/machina.js/wiki/machina.Fsm) (listed under the prototype members). In a nutshell, it allows you to say "I'm interested in this input, but I don't want to handle it until a different state". IME, I've found it useful in certain long-running async workflow scenarios or when using an FSM to control the order in which a flow is initialized, but the order of inputs can vary due to external circumstances beyond the FSM's ability to control.

(The above link is for the `Fsm` type, but it's also explained on the `BehavioralFsm` wiki page [here](https://github.com/ifandelse/machina.js/wiki/machina.BehavioralFsm)).
