### ISSUE TITLE
machine.transition('mystate',args...)

### ISSUE THREAD

**Issue by mnichols** [ifandelse/machina.js#40]
I frequently find my machines requiring transient properties to hold arguments from input handlers while myMachine.transition('toTheState') because `.transition` doesnt accept arguments and marshall them thru to the _onEnter of the next state.

It is trivial to pass along arguments from `.transition` into the _onEnter of the destination state, but before I submit a PR and such I wanted to make sure this isn't an intentional design decision.

This  would let you do

``` js

var Machine= machina.Fsm.extend({
    initialState: 'bar'
    ,states: {
        bar: {
            foo: function(args) {
                   this.transition('foo',args);
        }
        ,foo: {
            _onEnter: function(args) {
                //args === {please: 'includeme'}
                 this.thing = new MyThings(args)
            }
        }
    }
}

var machine = new Machine()
machine.handle('foo',{please:'includeme'})
```

**Comment by WishMasterGit** [comment]
Just in case someone still need state args, I did the fork and implemented this functionality for myself here (https://github.com/WishMasterGit/machina.js). I added new kind of machine called DynamicFsm, you can instantiate it through var fsm = new machina.DyncamicFsm(... . Then you can use it like this - fsm.transition("myState",data) and then in states _onEnter:function(fsm,data) or _onExit:function(fsm,data). While I agree with previous comments that this way is not best and in many scenarios goes against good practices, I found some scenarios when passing arguments to state quite good and useful and more over intuitive for developers.

**Comment by MichaelJCole** [comment]
Hey, I'm a bit frustrated by this choice.

After reading this I still don't know what deferUntilTransition() or deferAndTransition() do.  Is the defer() pattern similar to a Promise()?  Would renaming them .passArgumentsToTransition() be easier to learn?

I already know how to pass arguments as parameters to a function, so preventing/reinventing that is kinda whack.

My FSM is backed by a database.  The transitions create and pass [MongoDB update operators](https://docs.mongodb.org/manual/reference/operator/update/#id1) to `_onEnter()` so it can be saved along with the state.  Breaking that information into two database writes isn't going to work.  That information can't be rebuild from just the object.  If I was using another FSM implementation that didn't support passing parameters, it would be a problem there too.

Passing them on the object is clever if a bit hacky.  Debugging and researching this issue was much faster than building my own FSM, but seems less than optimal.

**Comment by sfrooster** [comment]
I stumbled on this thread while looking for a solution to my particular issue.  I haven't read the whole thing because it diverged from my need which, as I see it, is best served by the original question - passing arguments to _onEnter.

Specifically, I have an end state "Final" at/during which no more events should be accepted.  However, I do want to do some things whenever/however I arrive at this state ---> _onEnter!

Is there a best/better way to handle this?  If not, I'd like to cast my vote for _onEnter args (so I don't have to add "AdditionalInfo" fields to my state)...

**Comment by MichaelJCole** [comment]
@sfrooster I've been using the code in my previous comment for almost 2 months without problem.

**Comment by ifandelse** [comment]
I will finally have some time off in about a week to look into this. I've had enough folks ask about _onEnter args that I'm open to looking again :-) 

Apologies for the silence...I will def follow up! It's been a crazy few months. Really appreciate the feedback and questions!

**Comment by mnichols** [comment]
I'm the instigator of this so I'll weigh back in. :)
I think @ifandelse is still right about the decision to _not_ include args
in this kind of handler. I didnt include args on my own FSM impl that is
based on his api (https://github.com/mnichols/possum) for the same reasons
he pushed back...it keeps things simpler especially with deferrals, etc.
machina supports separation of state from behavior now so the issue to me
is minimized now.
So I still agree the burden is on the implementing code, not the framework,
to handle it. Just my $0.02.

**Comment by MichaelJCole** [comment]
@ifandelse No problem, it's open source, so same team :-)  I made a fork, but it was easier to use the hack above.
@mnichols awesome that works for you!  It does not work well for me.  Parameters would be optional anyways, so they are win-win for everyone.

Here's my use case: my state machines are backed by a MongoDB.  Because the copy in memory may have changed, I pass a `select` and `update` clause to _onEnter().  This let's the state machine selectively overwrite changes.  E.g.  update when { _id: 'someId', status: 'someStatus' }

To get that to onEnter, I think I need to pass parameters.  Without that, I'd need to put this logic in each input function.  It's hacked up using the code above.  I'm open to other implementations, but parameters seemed the most logical.

```
OpStates = _.extend(OpStates, {
  complete: {  // a state
    _onEnter: function(op) {
console.log('===> cancelled._onEnter');
      op.__args = op.__args || [];
      var update = op.__args[0] || {};
      var select = op.__args[1] || { _id: op._id, status: op.status };  // don't clobber other changes
      delete op.__args;

      console.log('-------- FIXME charging money w00t!');

      // Run Update
      var id = op._id;
      op = OpStates.saveStatus(op, update, select);
      if (!op) throw new Meteor.Error('complete state not activated: ' + id);
    },
  },
});
```

**Comment by ifandelse** [comment]
Bumping this thread to say that I've put together a release candidate [here](https://github.com/ifandelse/machina.js/blob/defect-hiearchical-rehydration/changelog.md#v200) that introduces support for arguments being passed to `_onEnter` (via the `transition` call) in addition to some other changes and fixes. I've been asked about adding this behavior a number of times from many different people - and I'd rather err in this case on the side of providing useful functionality, especially since it's not terribly prescriptive (you don't have to use it if you don't want to). I'm giving folks a day or two to check out the new branch and then I plan to release it as a breaking 2.0 change ("breaking" because of other changes included in that branch).

**Comment by MichaelJCole** [comment]
w00t!
