### ISSUE TITLE
Optionally pass an array of handlers

### ISSUE THREAD

**Issue by paulpdaniels** [ifandelse/machina.js#70]
In the current version if one has multiple handlers for an onExit or onEnter they have to be called like so

```javascript

_onExit : function() {
  handler1();
  handler2();
  //....
  handlerN();
}

```

It would be a nice bit of syntactic sugar to allow the onExit and onEnter properties to be either a function or an array of functions

```javascript

_onExit : [handler1, handler2, handler3]

```

**Comment by ifandelse** [comment]
Hi @paulpdaniels, I appreciate the feedback. By 'handlers', are you referring to feeding input to the FSM via the `this.handle` call (either directly or indirectly through a wrapper method)? Machina actually won't allow input handlers to be called in `_onExit` (they're no-op'd) because it could introduce a transition when the FSM is already transitioning to a new state. In my experience with FSMs in general, entry/exit actions are ideal for emitting events, or internal cleanup/setup. With that in mind, if this is code external to the FSM, reacting to events is a good approach to having n-number of observers execute behavior in those instances. If this is behavior internal to the FSM being invoked, I would be tempted to re-examine how I have the states/input broken down. The need to handle input in an `_onExit` handler might indicate there's another state that needs to be teased out. The need to handle input in an `_onEnter` (which machina definitely supports) may be just fine, though I'd recommend calling an explicit named handler...along these lines:

```javascript
_onEnter: function() {
    // great we made it, let's do stuff now
    this.emit("timeToDoStuff");
    this.handle("doStuff", 123);
},
doStuff: function(thingsToDo) {
    // doing all the things....
},
_onExit: function() {
    this.emit("doneDoneAndDone");
}
```

(forgive the contrived example)
All that long-winded way to say this - it would be helpful to understand the use case a bit more. Admittedly, my initial reaction is that allowing the entry/exit actions to be an array specifying method refs to invoke goes against the intention I had in implementing them. Hearing a more specific use case might help me offer an informed opinion. :smile:

**Comment by ifandelse** [comment]
Bumping this in case you want to weigh in  - no worries if not. Will close soon, but feel free to open another question issue, etc. if you need to.

**Comment by paulpdaniels** [comment]
@ifandelse Thanks for the look at this. The emitted event might be the way to go in this instance, though an array of handlers would provide more explicit ordering. My issue was I had a homespun FSM that supported adding N functions to the entry and exit handlers as an array.  Essentially some of the states shared set up and tear down steps while some needed custom steps injected in between. I was just looking for a way to port without inflicting to much change on the system.
