### ISSUE TITLE
Event .off(eventName) does not work when using .on(*, cb(e,d){})

### ISSUE THREAD

**Issue by javaknight** [ifandelse/machina.js#81]
Using the universal handler event catcher, then calling off on a specific event, doesn't work.

Ex:
trafficLight.on("*", function (eventName, data){
    console.log("this thing happened:", eventName);
});

trafficLight.off('handled');

Handled events are still being logged to console, meaning 'off' didn't turn it off.

**Comment by ifandelse** [comment]
@javaknight This is expected behavior, and most event emitter implementations that I'm aware of behave this way. Your observer subscribed to "*", which is provided for convenience to get the firehose of any event. Calling `off("handled")` will only unsubscribe all listeners that subscribed to that *specific* event. If you need to listen for, and the unsubscribe from a specific event, it's best to use the actual event name. Thanks!
